import { existsSync, mkdirSync, renameSync, rmSync } from 'node:fs';
import { mkdir, readdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const outDir = 'dist';
const dev = process.argv.includes('--dev');

// Full cross-platform matrix: linux / windows / macos x x64 / arm64.
const ALL_TARGETS = [
  { platform: 'linux', arch: 'x64', target: 'bun-linux-x64', out: `${outDir}/airlinkd-linux-x64` },
  { platform: 'linux', arch: 'arm64', target: 'bun-linux-arm64', out: `${outDir}/airlinkd-linux-arm64` },
  { platform: 'windows', arch: 'x64', target: 'bun-windows-x64', out: `${outDir}/airlinkd-windows-x64.exe` },
  { platform: 'windows', arch: 'arm64', target: 'bun-windows-arm64', out: `${outDir}/airlinkd-windows-arm64.exe` },
  { platform: 'macos', arch: 'x64', target: 'bun-darwin-x64', out: `${outDir}/airlinkd-macos-x64` },
  { platform: 'macos', arch: 'arm64', target: 'bun-darwin-arm64', out: `${outDir}/airlinkd-macos-arm64` },
];

// build:dev → single linux x64 binary named exactly `airlinkd`.
const targets = dev
  ? [{ platform: 'linux', arch: 'x64', target: 'bun-linux-x64', out: `${outDir}/airlinkd` }]
  : ALL_TARGETS;

const nativeTarget = ALL_TARGETS.find(
  (t) =>
    t.platform === (process.platform === 'win32' ? 'windows' : process.platform === 'darwin' ? 'macos' : 'linux') &&
    t.arch === process.arch,
);

// Runtime-only entries in storage/ that must never be bundled:
// the SFTP host key is generated on first start; alc/, containerConfigs/ and
// the stats/install logs are runtime state.
const RUNTIME_STORAGE = new Set([
  'sftp_host_ed25519',
  'alc',
  'containerConfigs',
  'install_logs.json',
  'systemStats.json',
]);

// Collect the storage files that ship inside the binary. Prefers the
// git-tracked set (self-maintaining); falls back to a directory walk when
// the build runs outside a git checkout.
async function collectStorageFiles(): Promise<string[]> {
  try {
    const { execSync } = await import('node:child_process');
    const listed = execSync('git ls-files storage/', { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] })
      .split('\n')
      .map((f) => f.trim())
      .filter(Boolean);
    if (listed.length > 0) return listed;
  } catch {
    /* not a git checkout — fall through to directory walk */
  }
  const walk = async (dir: string): Promise<string[]> => {
    const found: string[] = [];
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (RUNTIME_STORAGE.has(entry.name)) continue;
      if (entry.isDirectory()) found.push(...(await walk(path)));
      else found.push(path);
    }
    return found;
  };
  return walk('storage');
}

// Regenerate src/embedded.ts with the current storage defaults so the
// compiled binary always ships a byte-exact copy of the storage dir.
async function generateEmbeddedStorage(): Promise<void> {
  const files = await collectStorageFiles();
  const lines: string[] = [];
  for (const file of files) {
    const contents = await Bun.file(file).text();
    // JSON-escape, then wrap in single quotes (biome-compliant output so
    // regenerating never creates a formatting diff)
    const esc = (s: string) => JSON.stringify(s).slice(1, -1).replace(/'/g, "\\'");
    lines.push(`  {\n    path: '${esc(file)}',\n    contents: '${esc(contents)}',\n  },`);
  }
  const code = `// Auto-generated by build.ts — do not edit by hand.
// Contains the contents of the git-tracked storage/ directory so the
// standalone binary can extract its defaults on first run (see
// src/bootstrap.ts). Regenerated on every build.

export interface EmbeddedAsset {
  path: string;
  contents: string;
}

export const EMBEDDED_STORAGE: EmbeddedAsset[] = [
${lines.join('\n')}
];
`;
  await writeFile('src/embedded.ts', code);
  console.log(`embedded ${files.length} storage file(s) into src/embedded.ts`);
}

await generateEmbeddedStorage();

// @opentui/core loads its native renderer through per-platform packages
// (@opentui/core-linux-x64, -win32-arm64, ...) via dynamic import. bun build
// bundles every branch of that switch, so all platform packages must be
// resolvable from node_modules — but bun install skips the ones whose os/cpu
// don't match this host. Fetch the missing ones straight from the registry
// into node_modules for the duration of the build (they embed native libs
// into the binary, so each target gets its own renderer).
async function ensurePlatformPackages(): Promise<void> {
  const corePkg = JSON.parse(await Bun.file('node_modules/@opentui/core/package.json').text());
  const optional = (corePkg.optionalDependencies ?? {}) as Record<string, string>;
  for (const [name, version] of Object.entries(optional)) {
    const targetDir = `node_modules/${name}`;
    if (existsSync(`${targetDir}/package.json`)) continue;
    const bare = name.startsWith('@') ? name.split('/')[1] : name;
    const url = `https://registry.npmjs.org/${name}/-/${bare}-${version}.tgz`;
    console.log(`fetching ${name}@${version} from registry...`);
    const res = await fetch(url);
    if (!res.ok) throw new Error(`failed to fetch ${url}: HTTP ${res.status}`);
    const tarball = join(tmpdir(), `${bare}-${version}.tgz`);
    await Bun.write(tarball, await res.arrayBuffer());
    // extract inside node_modules so the rename stays on the same filesystem
    const extractDir = join('node_modules', '.opentui-staging');
    rmSync(extractDir, { recursive: true, force: true });
    mkdirSync(extractDir, { recursive: true });
    const { x: tarExtract } = await import('tar');
    await tarExtract({ file: tarball, cwd: extractDir });
    rmSync(tarball, { force: true });
    renameSync(join(extractDir, 'package'), targetDir);
    rmSync(extractDir, { recursive: true, force: true });
    console.log(`installed ${name}@${version} -> node_modules/${name}`);
  }
}

console.log(`checking TypeScript for${dev ? ' dev (linux x64)' : ' all targets'}...`);
const tscProc = Bun.spawn(['bunx', 'tsc', '--noEmit'], { stdout: 'inherit', stderr: 'inherit' });
const tscCode = await tscProc.exited;
if (tscCode !== 0) {
  console.error('TypeScript check failed');
  process.exit(1);
}
console.log('TypeScript check passed');

if (!dev) {
  await ensurePlatformPackages();
}

await mkdir(outDir, { recursive: true });
try {
  const { execSync } = await import('node:child_process');
  execSync(`rm -f ${outDir}/airlinkd ${outDir}/airlinkd-* 2>/dev/null`, { stdio: 'ignore' });
} catch {
  /* nothing to clean */
}

// Stub native .node modules before building.
// Bun standalone binaries crash on dlopen of .node files.
// The daemon only uses local Docker sockets, so SSH transport is never needed.

// 1. Stub cpu-features (required by ssh2)
await writeFile(
  'node_modules/cpu-features/lib/index.js',
  'module.exports = function() { return { flags: [], models: [] }; };\n',
);
console.log('patched cpu-features');

// 2. Stub ssh2 native crypto binding
// ssh2 wraps the require in try/catch, but Bun crashes during the dlopen
// itself. We remove the require entirely so ssh2 falls back to JS crypto.
const sshCryptoPath = 'node_modules/ssh2/lib/protocol/crypto.js';
const orig = await Bun.file(sshCryptoPath).text();
if (orig.includes("require('./crypto/build/Release/sshcrypto.node')")) {
  const patched = orig.replace(
    /binding = require\('\.\/crypto\/build\/Release\/sshcrypto\.node'\);/,
    'binding = null; // stubbed: native .node crashes Bun standalone',
  );
  await writeFile(sshCryptoPath, patched);
  console.log('patched ssh2 crypto binding');
}

// 3. Remove .node files so bun build --compile can't try to embed them
try {
  const { execSync } = await import('node:child_process');
  execSync('find node_modules -name "*.node" -delete 2>/dev/null', { stdio: 'ignore' });
  console.log('removed .node files');
} catch {
  /* ignore */
}

for (const { target, out } of targets) {
  console.log(`building ${out}...`);
  const proc = Bun.spawn(['bun', 'build', '--compile', '--target', target, '--outfile', out, 'src/app.ts'], {
    stdout: 'inherit',
    stderr: 'inherit',
  });
  const code = await proc.exited;
  if (code !== 0) console.error(`build failed for ${target}`);
  else console.log(`built ${out}`);
}

if (!dev && nativeTarget) {
  await import('node:fs/promises').then(({ copyFile }) => copyFile(nativeTarget.out, `${outDir}/airlinkd`));
  console.log(`copied ${nativeTarget.out} -> ${outDir}/airlinkd`);
}
