/**
 * Stats collection constants.
 */

export {
  CPU_SAMPLE_INTERVAL_MS,
  STATS_MAX_AGE_MS,
  STATS_HEALTH_CHECK_TIMEOUT_MS,
  NODE_STATS_POLL_MS,
  CONTAINER_STATUS_POLL_MS,
} from "./timeouts";

export {
  STATS_MAX_ENTRIES,
  DAEMON_STATS_PREV_PROCS_CAP,
  DAEMON_STATS_TOP_PROCS_LIMIT,
  DAEMON_ERROR_LOG_TAIL_CAP,
  DAEMON_ERROR_COUNT_CUTOFF_MS,
  HOST_MAX_DISKS,
  HOST_MAX_NETWORK_INTERFACES,
  HOST_MAX_DISK_IO_DEVICES,
  HOST_MAX_THERMAL_ZONES,
  NODE_STATS_HISTORY_SLICE,
} from "./limits";
